"""item images on delete cascade

Revision ID: 00291ebf5b68
Revises: 01571124976b
Create Date: 2025-11-17 09:15:52.673983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00291ebf5b68'
down_revision: Union[str, Sequence[str], None] = '01571124976b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('product_images_item_id_fkey'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'items', ['item_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_item_id_fkey'), 'product_images', 'items', ['item_id'], ['id'])
    # ### end Alembic commands ###
