"""add more details to items, and multiple images

Revision ID: 01571124976b
Revises: 33e3757f3727
Create Date: 2025-11-17 09:06:35.948756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01571124976b'
down_revision: Union[str, Sequence[str], None] = '33e3757f3727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('image_url_suffix', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.add_column('items', sa.Column('designer_name', sa.String(), nullable=True))
    op.add_column('items', sa.Column('price', sa.String(), nullable=True))
    op.add_column('items', sa.Column('color', sa.String(), nullable=True))
    op.add_column('items', sa.Column('stretch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'stretch')
    op.drop_column('items', 'color')
    op.drop_column('items', 'price')
    op.drop_column('items', 'designer_name')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
