"""add separate image id for db

Revision ID: 14e8f66bf8a8
Revises: ae4113dd9587
Create Date: 2025-11-17 14:11:43.395305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e8f66bf8a8'
down_revision: Union[str, Sequence[str], None] = 'ae4113dd9587'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("product_images", "id")
    op.add_column("product_images", sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_images', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('product_images_id_seq'::regclass)"))
    # ### end Alembic commands ###
