"""add product detail url to items table

Revision ID: 33e3757f3727
Revises: 04fc7627e9c4
Create Date: 2025-11-05 16:48:25.445643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e3757f3727'
down_revision: Union[str, Sequence[str], None] = '04fc7627e9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('product_detail_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'product_detail_url')
    # ### end Alembic commands ###
