"""add user like outfit table

Revision ID: 3aeee3304299
Revises: 9a2f3522a93a
Create Date: 2025-12-05 17:24:41.143986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aeee3304299'
down_revision: Union[str, Sequence[str], None] = '9a2f3522a93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_like_outfits',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('outfit_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'outfit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_like_outfits')
    # ### end Alembic commands ###
