"""remove_show_in_closet

Revision ID: 55f72e278457
Revises: e5e7ee900c10
Create Date: 2025-11-27 12:37:59.481077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f72e278457'
down_revision: Union[str, Sequence[str], None] = 'e5e7ee900c10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_like_items', 'show_in_closet')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_like_items', sa.Column('show_in_closet', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
