"""add like timestamp to liked items

Revision ID: 584a9b1f2d3c
Revises: 14e8f66bf8a8
Create Date: 2025-11-24 17:25:29.298234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584a9b1f2d3c'
down_revision: Union[str, Sequence[str], None] = '14e8f66bf8a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.add_column('user_like_items', sa.Column('like_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_like_items', 'like_timestamp')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    # ### end Alembic commands ###
