"""added detailed embedding column

Revision ID: 83f580831464
Revises: 55f72e278457
Create Date: 2025-11-29 11:21:26.053543

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83f580831464'
down_revision: Union[str, Sequence[str], None] = '55f72e278457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('detailed_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'detailed_embedding')
    # ### end Alembic commands ###
