"""add show in closet column to the user liked items table

Revision ID: 851f3a97d69e
Revises: 859ab159181c
Create Date: 2025-10-31 17:02:12.089345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '851f3a97d69e'
down_revision: Union[str, Sequence[str], None] = '859ab159181c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_like_items', sa.Column('show_in_closet', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_like_items', 'show_in_closet')
    # ### end Alembic commands ###
