"""Add embedding column to item table

Revision ID: cb7883ca023e
Revises: 9b1c0453da6c
Create Date: 2025-10-27 15:51:52.249480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'cb7883ca023e'
down_revision: Union[str, Sequence[str], None] = '9b1c0453da6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('embedding', Vector(dim=768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'embedding')
    # ### end Alembic commands ###
