"""store image url suffix for item and outfit

Revision ID: cd5026da6d98
Revises: 552a22f6a3ed
Create Date: 2025-10-15 16:02:32.848702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5026da6d98'
down_revision: Union[str, Sequence[str], None] = '552a22f6a3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('image_url_suffix', sa.String(), nullable=True))
    op.add_column('outfits', sa.Column('image_url_suffix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outfits', 'image_url_suffix')
    op.drop_column('items', 'image_url_suffix')
    # ### end Alembic commands ###
