"""Added relationship for items to liked and disliked users

Revision ID: d8a6680f7783
Revises: cb7883ca023e
Create Date: 2025-10-27 16:47:12.309284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a6680f7783'
down_revision: Union[str, Sequence[str], None] = 'cb7883ca023e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
